language: generic

matrix:
  include:
    # - os: osx
    #   osx_image: xcode11.3
    #   before_install:
    #     # - brew update
    #     # - brew tap caskroom/cask
    #     - brew cask install powershell
    - os: linux
      dist: bionic
      # VM-based builds turned out to be faster
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod trusty main

script: |
  wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.0/powershell-lts_7.0.0-1.ubuntu.18.04_amd64.deb
  sudo dpkg -i powershell-lts_7.0.0-1.ubuntu.18.04_amd64.deb
  sudo apt-get install -f
  pwsh -c "& ./test.ps1 -ci -passThru"

