language: csharp
mono: none
dotnet: 3.1.201

env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
    - os: linux
      dist: bionic

script:
  - dotnet tool install --global PowerShell
  - pwsh -c "./test.ps1 -ci -passThru"

