trigger:
  - v5.0
pr:
  - v5.0

resources:
  - repo: self
    clean: true
    fetchDepth: 1

jobs:
  - job: ps3
    displayName: PowerShell 3
    continueOnError: false
    pool:
      name: Default
      demands:
        - dotnet
        - ps3
    workspace:
      clean: all
    timeoutInMinutes: 3
    steps:
      - powershell: ./test.ps1 -CI -PassThru

  - job: ubups7
    pool:
      vmImage: 'ubuntu-16.04'
    container: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - pwsh: ./test.ps1 -CI -PassThru

