trigger:
  - v5.0
pr:
  - v5.0

resources:
  - repo: self
    clean: true
    fetchDepth: 1

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: build
        pool:
          name: Default
          demands:
            - net452
            - netcoreapp3.1
        timeoutInMinutes: 3
        steps:
          - powershell: ./build.ps1
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact: bin Folder'
            inputs:
              targetPath: '$(Build.SourcesDirectory)/bin'
              artifactName: bin